// <auto-generated />
using System;
using BackendSis7.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendSis7.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20241228222156_egg")]
    partial class egg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BackendSis7.Models.Administrador", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("email");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BackendSis7.Models.Empleado", b =>
                {
                    b.Property<Guid>("IdTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AFPNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CargasFamiliares")
                        .HasColumnType("INTEGER");

                    b.Property<string>("isapreNombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tipoContrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTrabajador");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("BackendSis7.Models.Sueldo", b =>
                {
                    b.Property<Guid>("IdTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("HorasExtra")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SueldoBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SueldoFinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTrabajador");

                    b.ToTable("Sueldos");
                });
#pragma warning restore 612, 618
        }
    }
}
